pipeline {
    agent any

    stages {
        stage('Clone code') {
            steps {
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'git-creds', url: 'https://github.com/SaitejaVarada1122/JenkinsWithDocker.git']])
            }
        }
        stage('build'){
            steps{
                dir('sampleapp'){
                    bat 'mvn clean package'
                }
            }
        }
        stage('Build Docker Image') {
    steps {
        dir('sampleapp'){
        bat 'docker build -t saitejavarada/jenkinswithdocker:0.V1 .'
        }
    }
}
    stage('Push to DockerHub')
    {
        steps{
            withCredentials([usernameColonPassword(credentialsId: 'credsdocker', variable: 'dockercreds')]) {
            bat 'docker push saitejavarada/jenkinswithdocker:0.V1'
    }
            
        }
    }
    stage('Run Container'){
		steps{
					// Stop old container if exists
                    bat 'docker stop spring-app || true'
                    bat 'docker rm spring-app || true'
                    
                    // Run new container
                    bat 'docker run -d -p 9124:9123 --name spring-app saitejavarada/jenkinswithdocker:0.V1'
                
		}
	}
    }
}
